### ISSUE TITLE
create a cookbook generator template file to use with `chef generate cookbook`

### ISSUE THREAD

**Issue by ricardolupo** [chef-partners/cookbook-guide#16]
As a user, i want to consume the best practices to create cookbooks in a repeatable way. Having a custom cookbook generator that I can source via `chef generate cookbook <foo> -g <foogenerator>` in a repeatable way.

**Comment by jjasghar** [comment]
👍 Great idea. I'm going to make this happen ASAP.

**Comment by jjasghar** [comment]
Looks like @echohack has created https://medium.com/@echohack/creating-your-own-chef-cookbook-generator-5e998db1255b#.vteyjkn7r as a good reference point.

**Comment by jjasghar** [comment]
@ricardolupo i think this is what you're looking for: https://github.com/chef-partners/cookbook-guide-generator
